CREATE VIEW doktor_login as
select doktor_ID, doktor_mail, doktor_SIFRE from doktorlar;

CREATE VIEW UZMANLIK as
SELECT DOKTORLAR.DOKTOR_ID, DOKTORLAR.DOKTOR_ISIM, DOKTORLAR.DOKTOR_SOYISIM, UZMANLIKLAR.UZMANLIK_ISIM
from DOKTOR_UZMANLIK_LISTESI INNER JOIN DOKTORLAR on DOKTOR_UZMANLIK_LISTESI.DOKTOR_ID=DOKTORLAR.DOKTOR_ID
							 INNER JOIN UZMANLIKLAR on DOKTOR_UZMANLIK_LISTESI.UZMANLIK_ID=UZMANLIKLAR.UZMANLIK_ID;
							 
CREATE VIEW AnaBilim as
SELECT DOKTORLAR.DOKTOR_ID, DOKTORLAR.DOKTOR_ISIM, DOKTORLAR.DOKTOR_SOYISIM, ABD.ABD_ISIM
from DOKTOR_ABD_LISTESI INNER JOIN DOKTORLAR on DOKTOR_ABD_LISTESI.DOKTOR_ID=DOKTORLAR.DOKTOR_ID
						INNER JOIN ABD on DOKTOR_ABD_LISTESI.ABD_ID=ABD.ABD_ID;